steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/fyj/fahari-dashboards-${_DEPLOYMENT_TYPE}:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/fyj/fahari-dashboards-${_DEPLOYMENT_TYPE}:$COMMIT_SHA"]

  # Deploy an image from Container Registry to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "beta",
      "run",
      "deploy",
      "${_SERVICE_NAME}",
      "--image", "europe-west1-docker.pkg.dev/$PROJECT_ID/fyj/fahari-dashboards-${_DEPLOYMENT_TYPE}:$COMMIT_SHA",
      "--region", "europe-west1",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--set-env-vars", "GOOGLE_CLOUD_PROJECT=$PROJECT_ID",
      "--min-instances", "1",
      "--max-instances", "8",
      "--memory", "512M",
      "--cpu", "1",
      # "--set-secrets", "/tmp/secrets/.env=${_SETTINGS_NAME}:latest",
      "--timeout", "59m59s"
  ]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/fyj/fahari-dashboards-${_DEPLOYMENT_TYPE}:$COMMIT_SHA"

timeout: 1200s
queueTtl: 3600s